/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fr.gleo.meetup.liferay.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import fr.gleo.meetup.liferay.model.Cocktail;
import fr.gleo.meetup.liferay.service.CocktailLocalService;
import fr.gleo.meetup.liferay.service.persistence.CocktailPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cocktail local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link fr.gleo.meetup.liferay.service.impl.CocktailLocalServiceImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see fr.gleo.meetup.liferay.service.impl.CocktailLocalServiceImpl
 * @generated
 */
public abstract class CocktailLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CocktailLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CocktailLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>fr.gleo.meetup.liferay.service.CocktailLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cocktail to the database. Also notifies the appropriate model listeners.
	 *
	 * @param cocktail the cocktail
	 * @return the cocktail that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Cocktail addCocktail(Cocktail cocktail) {
		cocktail.setNew(true);

		return cocktailPersistence.update(cocktail);
	}

	/**
	 * Creates a new cocktail with the primary key. Does not add the cocktail to the database.
	 *
	 * @param cocktailId the primary key for the new cocktail
	 * @return the new cocktail
	 */
	@Override
	@Transactional(enabled = false)
	public Cocktail createCocktail(long cocktailId) {
		return cocktailPersistence.create(cocktailId);
	}

	/**
	 * Deletes the cocktail with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param cocktailId the primary key of the cocktail
	 * @return the cocktail that was removed
	 * @throws PortalException if a cocktail with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Cocktail deleteCocktail(long cocktailId) throws PortalException {
		return cocktailPersistence.remove(cocktailId);
	}

	/**
	 * Deletes the cocktail from the database. Also notifies the appropriate model listeners.
	 *
	 * @param cocktail the cocktail
	 * @return the cocktail that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Cocktail deleteCocktail(Cocktail cocktail) {
		return cocktailPersistence.remove(cocktail);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Cocktail.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cocktailPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>fr.gleo.meetup.liferay.model.impl.CocktailModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cocktailPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>fr.gleo.meetup.liferay.model.impl.CocktailModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cocktailPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cocktailPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cocktailPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Cocktail fetchCocktail(long cocktailId) {
		return cocktailPersistence.fetchByPrimaryKey(cocktailId);
	}

	/**
	 * Returns the cocktail matching the UUID and group.
	 *
	 * @param uuid the cocktail's UUID
	 * @param groupId the primary key of the group
	 * @return the matching cocktail, or <code>null</code> if a matching cocktail could not be found
	 */
	@Override
	public Cocktail fetchCocktailByUuidAndGroupId(String uuid, long groupId) {
		return cocktailPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the cocktail with the primary key.
	 *
	 * @param cocktailId the primary key of the cocktail
	 * @return the cocktail
	 * @throws PortalException if a cocktail with the primary key could not be found
	 */
	@Override
	public Cocktail getCocktail(long cocktailId) throws PortalException {
		return cocktailPersistence.findByPrimaryKey(cocktailId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(cocktailLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Cocktail.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("cocktailId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cocktailLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Cocktail.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("cocktailId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(cocktailLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Cocktail.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("cocktailId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Cocktail>() {

				@Override
				public void performAction(Cocktail cocktail)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, cocktail);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Cocktail.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return cocktailLocalService.deleteCocktail((Cocktail)persistedModel);
	}

	public BasePersistence<Cocktail> getBasePersistence() {
		return cocktailPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cocktailPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the cocktails matching the UUID and company.
	 *
	 * @param uuid the UUID of the cocktails
	 * @param companyId the primary key of the company
	 * @return the matching cocktails, or an empty list if no matches were found
	 */
	@Override
	public List<Cocktail> getCocktailsByUuidAndCompanyId(
		String uuid, long companyId) {

		return cocktailPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of cocktails matching the UUID and company.
	 *
	 * @param uuid the UUID of the cocktails
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of cocktails
	 * @param end the upper bound of the range of cocktails (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching cocktails, or an empty list if no matches were found
	 */
	@Override
	public List<Cocktail> getCocktailsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Cocktail> orderByComparator) {

		return cocktailPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the cocktail matching the UUID and group.
	 *
	 * @param uuid the cocktail's UUID
	 * @param groupId the primary key of the group
	 * @return the matching cocktail
	 * @throws PortalException if a matching cocktail could not be found
	 */
	@Override
	public Cocktail getCocktailByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return cocktailPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the cocktails.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>fr.gleo.meetup.liferay.model.impl.CocktailModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cocktails
	 * @param end the upper bound of the range of cocktails (not inclusive)
	 * @return the range of cocktails
	 */
	@Override
	public List<Cocktail> getCocktails(int start, int end) {
		return cocktailPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cocktails.
	 *
	 * @return the number of cocktails
	 */
	@Override
	public int getCocktailsCount() {
		return cocktailPersistence.countAll();
	}

	/**
	 * Updates the cocktail in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param cocktail the cocktail
	 * @return the cocktail that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Cocktail updateCocktail(Cocktail cocktail) {
		return cocktailPersistence.update(cocktail);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CocktailLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		cocktailLocalService = (CocktailLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CocktailLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Cocktail.class;
	}

	protected String getModelClassName() {
		return Cocktail.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = cocktailPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CocktailLocalService cocktailLocalService;

	@Reference
	protected CocktailPersistence cocktailPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.GroupLocalService
		groupLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService
		workflowInstanceLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService
		assetLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}